version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

  api-server:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - "./src:/app"
    ports:
      - "4000:4000"

    depends_on:
      - mongodb
    links:
      - mongodb
    logging:
      options:
        max-size: "1m"
        max-file: "1"

  mongodb:
    container_name: mongodb_exam_service
    image: mongo:4
    restart: always
    # command: mongod --port 37017

    logging:
      options:
        max-size: "1m"
        max-file: "1"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
